# Generated by Django 3.2.9 on 2021-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_myblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
