# Generated by Django 3.2.9 on 2021-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211216_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
